// scripts/build_foods_sql.py が生成します。手で編集しないでください。
export const FOODS_COLUMNS = ["food_no", "group_code", "index_no", "name", "refuse", "enerc", "enerc_kcal", "water", "protcaa", "prot", "fatnlea", "chole", "fat", "choavlm", "choavl", "choavldf", "fib", "polyl", "chocdf", "oa", "ash", "na", "k", "ca", "mg", "p", "fe", "zn", "cu", "mn", "iodine", "se", "cr", "mo", "retol", "carta", "cartb", "crypxb", "cartbeq", "vita_rae", "vitd", "tocpha", "tocphb", "tocphg", "tocphd", "vitk", "thia", "ribf", "nia", "ne", "vitb6a", "vitb12", "fol", "pantac", "biot", "vitc", "alc", "nacl_eq", "note"];
export const DDL = [
  "CREATE TABLE IF NOT EXISTS food_groups (group_code TEXT PRIMARY KEY, group_name TEXT NOT NULL)",
  "CREATE TABLE IF NOT EXISTS foods (food_no TEXT PRIMARY KEY, group_code TEXT NOT NULL, index_no TEXT, name TEXT NOT NULL, refuse REAL, enerc REAL, enerc_kcal REAL, water REAL, protcaa REAL, prot REAL, fatnlea REAL, chole REAL, fat REAL, choavlm REAL, choavl REAL, choavldf REAL, fib REAL, polyl REAL, chocdf REAL, oa REAL, ash REAL, na REAL, k REAL, ca REAL, mg REAL, p REAL, fe REAL, zn REAL, cu REAL, mn REAL, iodine REAL, se REAL, cr REAL, mo REAL, retol REAL, carta REAL, cartb REAL, crypxb REAL, cartbeq REAL, vita_rae REAL, vitd REAL, tocpha REAL, tocphb REAL, tocphg REAL, tocphd REAL, vitk REAL, thia REAL, ribf REAL, nia REAL, ne REAL, vitb6a REAL, vitb12 REAL, fol REAL, pantac REAL, biot REAL, vitc REAL, alc REAL, nacl_eq REAL, note TEXT)",
  "CREATE INDEX IF NOT EXISTS idx_foods_group ON foods(group_code)",
  "CREATE TABLE IF NOT EXISTS nutrient_defs (code TEXT PRIMARY KEY, \"column\" TEXT NOT NULL, label TEXT NOT NULL, unit TEXT NOT NULL, sort_no INTEGER NOT NULL)"
];
export const GROUPS = [["01", "穀類"], ["02", "いも及びでん粉類"], ["03", "砂糖及び甘味類"], ["04", "豆類"], ["05", "種実類"], ["06", "野菜類"], ["07", "果実類"], ["08", "きのこ類"], ["09", "藻類"], ["10", "魚介類"], ["11", "肉類"], ["12", "卵類"], ["13", "乳類"], ["14", "油脂類"], ["15", "菓子類"], ["16", "し好飲料類"], ["17", "調味料及び香辛料類"], ["18", "調理済み流通食品類"]];
export const NUTRIENT_DEFS = [["REFUSE", "refuse", "廃棄率", "%", 1], ["ENERC", "enerc", "エネルギー", "kJ", 2], ["ENERC_KCAL", "enerc_kcal", "エネルギー", "kcal", 3], ["WATER", "water", "水分", "g", 4], ["PROTCAA", "protcaa", "アミノ酸組成によるたんぱく質", "g", 5], ["PROT-", "prot", "たんぱく質", "g", 6], ["FATNLEA", "fatnlea", "脂肪酸のトリアシルグリセロール当量", "g", 7], ["CHOLE", "chole", "コレステロール", "mg", 8], ["FAT-", "fat", "脂質", "g", 9], ["CHOAVLM", "choavlm", "利用可能炭水化物(単糖当量)", "g", 10], ["CHOAVL", "choavl", "利用可能炭水化物(質量計)", "g", 11], ["CHOAVLDF-", "choavldf", "差引き法による利用可能炭水化物", "g", 12], ["FIB-", "fib", "食物繊維総量", "g", 13], ["POLYL", "polyl", "糖アルコール", "g", 14], ["CHOCDF-", "chocdf", "炭水化物", "g", 15], ["OA", "oa", "有機酸", "g", 16], ["ASH", "ash", "灰分", "g", 17], ["NA", "na", "ナトリウム", "mg", 18], ["K", "k", "カリウム", "mg", 19], ["CA", "ca", "カルシウム", "mg", 20], ["MG", "mg", "マグネシウム", "mg", 21], ["P", "p", "リン", "mg", 22], ["FE", "fe", "鉄", "mg", 23], ["ZN", "zn", "亜鉛", "mg", 24], ["CU", "cu", "銅", "mg", 25], ["MN", "mn", "マンガン", "mg", 26], ["ID", "iodine", "ヨウ素", "μg", 27], ["SE", "se", "セレン", "μg", 28], ["CR", "cr", "クロム", "μg", 29], ["MO", "mo", "モリブデン", "μg", 30], ["RETOL", "retol", "レチノール", "μg", 31], ["CARTA", "carta", "α-カロテン", "μg", 32], ["CARTB", "cartb", "β-カロテン", "μg", 33], ["CRYPXB", "crypxb", "β-クリプトキサンチン", "μg", 34], ["CARTBEQ", "cartbeq", "β-カロテン当量", "μg", 35], ["VITA_RAE", "vita_rae", "レチノール活性当量", "μg", 36], ["VITD", "vitd", "ビタミンD", "μg", 37], ["TOCPHA", "tocpha", "α-トコフェロール", "mg", 38], ["TOCPHB", "tocphb", "β-トコフェロール", "mg", 39], ["TOCPHG", "tocphg", "γ-トコフェロール", "mg", 40], ["TOCPHD", "tocphd", "δ-トコフェロール", "mg", 41], ["VITK", "vitk", "ビタミンK", "μg", 42], ["THIA", "thia", "ビタミンB1", "mg", 43], ["RIBF", "ribf", "ビタミンB2", "mg", 44], ["NIA", "nia", "ナイアシン", "mg", 45], ["NE", "ne", "ナイアシン当量", "mg", 46], ["VITB6A", "vitb6a", "ビタミンB6", "mg", 47], ["VITB12", "vitb12", "ビタミンB12", "μg", 48], ["FOL", "fol", "葉酸", "μg", 49], ["PANTAC", "pantac", "パントテン酸", "mg", 50], ["BIOT", "biot", "ビオチン", "μg", 51], ["VITC", "vitc", "ビタミンC", "mg", 52], ["ALC", "alc", "アルコール", "g", 53], ["NACL_EQ", "nacl_eq", "食塩相当量", "g", 54]];
